spring:
  profiles:
    active: ${APP_PROFILE:json}
server:
  port: 8080
jwt:
  secret: ${JWT_SECRET}
carrent:
  json:
    users-file: users.json
    vehicles-file: vehicles.json
    rentals-file: rentals.json
    categories-file: categories.json